Dereference pointers when comparing MaintainerCanModify
mattermost/mattermost-mattermod pull request #260
Opened 2021-03-17 08:31 UTC by msal4

#### Summary
Right now we're comparing pointers which is probably not the behavior we want

```go
// server/pull_request_handler.go

//...
if oldPr.MaintainerCanModify == nil || (oldPr.MaintainerCanModify != pr.MaintainerCanModify) {
	prHasChanges = true
}
//...
```
I was gonna commit the change in #258 but I wasn't quick enough :)
#### Ticket Link
JIRA: https://mattermost.atlassian.net/browse/MM-26814

2021-03-17 08:32 UTC, mattermod commented
Hello @msal4,

Thanks for your pull request! A Core Committer will review your pull request soon. For code contributions, you can learn more about the review process [here](https://developers.mattermost.com/contribute/getting-started/code-review/).

2021-03-17 08:36 UTC, agnivade requested changes
Woops, nice catch! Can we write a test for this please so that the behavior does not regress again?

2021-03-20 14:14 UTC, msal4 commented
I think these should do it.
I'll do a separate PR after this one is merged to update `Merged, MaintainerCanModify, MilestoneNumber, MilestoneTitle` to be `*type ` since the changes are related and minuscule.

2021-03-20 17:11 UTC, agnivade commented on server/pull_request_handler_test.go
> +			MaintainerCanModify: NewBool(false),
I'd prefer to do a `!` here too to be consistent and more robust.

2021-03-21 03:53 UTC, agnivade approved these changes

2021-03-22 17:26 UTC, isacikgoz approved these changes
LGTM 👍  Thanks for the unit tests.

2021-03-23 08:17 UTC, merged